language: r
cache: packages
# pandoc_version: 1.19.2.1

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev

#before_script:
#  - chmod +x ./_build.sh
#  - chmod +x ./_deploy_to_staging.sh

before_install:
  - git config --global user.email "baydap@gmail.com"
  - git config --global user.name "pzhaonet"

script:
  - bash scripts/_build.sh

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    
after_success:
  - git add -A
  - git commit -m"travis update"
  - git push -q https://${GITHUB_PAT}@github.com/pzhaonet/dph206-2020.git HEAD:master